//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreClic.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PreClic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dans le répertoire.
        /// </summary>
        internal static string dans_le_répertoire {
            get {
                return ResourceManager.GetString("dans_le_répertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while loading the.
        /// </summary>
        internal static string Error_while_loading_the {
            get {
                return ResourceManager.GetString("Error_while_loading_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de créer le fichier.
        /// </summary>
        internal static string Impossible_de_créer_le_fichier {
            get {
                return ResourceManager.GetString("Impossible_de_créer_le_fichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;url est manquante.
        /// </summary>
        internal static string L_url_est_manquante {
            get {
                return ResourceManager.GetString("L_url_est_manquante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la création du fichier ini.
        /// </summary>
        internal static string Une_erreur_s_est_produite_lors_de_la_création_du_fichier_ini {
            get {
                return ResourceManager.GetString("Une_erreur_s_est_produite_lors_de_la_création_du_fichier_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la lecture du fichier csv..
        /// </summary>
        internal static string Une_erreur_s_est_produite_lors_de_la_lecture_du_fichier_csv {
            get {
                return ResourceManager.GetString("Une_erreur_s_est_produite_lors_de_la_lecture_du_fichier_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez lancer le chargement du fichier avant la vérification.
        /// </summary>
        internal static string Vous_devez_lancer_le_chargement_du_fichier_avant_la_vérification {
            get {
                return ResourceManager.GetString("Vous_devez_lancer_le_chargement_du_fichier_avant_la_vérification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML file.
        /// </summary>
        internal static string XML_file {
            get {
                return ResourceManager.GetString("XML_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your XML file has duplicate like.
        /// </summary>
        internal static string Your_XML_file_has_duplicate_like {
            get {
                return ResourceManager.GetString("Your_XML_file_has_duplicate_like", resourceCulture);
            }
        }
    }
}
